### ISSUE TITLE
Science filters link broken in documentation

### ISSUE THREAD

**Issue by anaismoller** [astrolabsoftware/fink#49]
Science filter link is broken https://fink-broker.readthedocs.io/en/latest/science/filters/ 

Pointed from: https://fink-broker.readthedocs.io/en/latest/services/livestream/#purpose

**Comment by JulienPeloton** [comment]
Thanks @anaismoller ! The link has been fixed. The list of topics is at https://fink-broker.readthedocs.io/en/latest/broker/filters/#available-topics
